//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ReportWatchModel", "FK_Day_Symbol", "SymbolSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportWatch.Database.Symbol), "DayPriceSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportWatch.Database.DayPrice), true)]
[assembly: EdmRelationshipAttribute("ReportWatchModel", "FK_Report_Symbol", "SymbolSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportWatch.Database.Symbol), "ReportSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportWatch.Database.Report), true)]

#endregion

namespace ReportWatch.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReportWatchEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReportWatchEntities object using the connection string found in the 'ReportWatchEntities' section of the application configuration file.
        /// </summary>
        public ReportWatchEntities() : base("name=ReportWatchEntities", "ReportWatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReportWatchEntities object.
        /// </summary>
        public ReportWatchEntities(string connectionString) : base(connectionString, "ReportWatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReportWatchEntities object.
        /// </summary>
        public ReportWatchEntities(EntityConnection connection) : base(connection, "ReportWatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DayPrice> DayPriceSet
        {
            get
            {
                if ((_DayPriceSet == null))
                {
                    _DayPriceSet = base.CreateObjectSet<DayPrice>("DayPriceSet");
                }
                return _DayPriceSet;
            }
        }
        private ObjectSet<DayPrice> _DayPriceSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExceptionLog> ExceptionLogSet
        {
            get
            {
                if ((_ExceptionLogSet == null))
                {
                    _ExceptionLogSet = base.CreateObjectSet<ExceptionLog>("ExceptionLogSet");
                }
                return _ExceptionLogSet;
            }
        }
        private ObjectSet<ExceptionLog> _ExceptionLogSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Report> ReportSet
        {
            get
            {
                if ((_ReportSet == null))
                {
                    _ReportSet = base.CreateObjectSet<Report>("ReportSet");
                }
                return _ReportSet;
            }
        }
        private ObjectSet<Report> _ReportSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Symbol> SymbolSet
        {
            get
            {
                if ((_SymbolSet == null))
                {
                    _SymbolSet = base.CreateObjectSet<Symbol>("SymbolSet");
                }
                return _SymbolSet;
            }
        }
        private ObjectSet<Symbol> _SymbolSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DayPriceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDayPriceSet(DayPrice dayPrice)
        {
            base.AddObject("DayPriceSet", dayPrice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExceptionLogSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExceptionLogSet(ExceptionLog exceptionLog)
        {
            base.AddObject("ExceptionLogSet", exceptionLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReportSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReportSet(Report report)
        {
            base.AddObject("ReportSet", report);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SymbolSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSymbolSet(Symbol symbol)
        {
            base.AddObject("SymbolSet", symbol);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportWatchModel", Name="DayPrice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DayPrice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DayPrice object.
        /// </summary>
        /// <param name="dayPriceId">Initial value of the DayPriceId property.</param>
        /// <param name="symbolName">Initial value of the SymbolName property.</param>
        /// <param name="dayPriceDate">Initial value of the DayPriceDate property.</param>
        /// <param name="dayPriceOpen">Initial value of the DayPriceOpen property.</param>
        /// <param name="dayPriceHigh">Initial value of the DayPriceHigh property.</param>
        /// <param name="dayPriceLow">Initial value of the DayPriceLow property.</param>
        /// <param name="dayPriceClose">Initial value of the DayPriceClose property.</param>
        /// <param name="dayPriceAdjustedClose">Initial value of the DayPriceAdjustedClose property.</param>
        /// <param name="dayPriceVolume">Initial value of the DayPriceVolume property.</param>
        public static DayPrice CreateDayPrice(global::System.Guid dayPriceId, global::System.String symbolName, global::System.DateTime dayPriceDate, global::System.Decimal dayPriceOpen, global::System.Decimal dayPriceHigh, global::System.Decimal dayPriceLow, global::System.Decimal dayPriceClose, global::System.Decimal dayPriceAdjustedClose, global::System.Int64 dayPriceVolume)
        {
            DayPrice dayPrice = new DayPrice();
            dayPrice.DayPriceId = dayPriceId;
            dayPrice.SymbolName = symbolName;
            dayPrice.DayPriceDate = dayPriceDate;
            dayPrice.DayPriceOpen = dayPriceOpen;
            dayPrice.DayPriceHigh = dayPriceHigh;
            dayPrice.DayPriceLow = dayPriceLow;
            dayPrice.DayPriceClose = dayPriceClose;
            dayPrice.DayPriceAdjustedClose = dayPriceAdjustedClose;
            dayPrice.DayPriceVolume = dayPriceVolume;
            return dayPrice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DayPriceId
        {
            get
            {
                return _DayPriceId;
            }
            set
            {
                if (_DayPriceId != value)
                {
                    OnDayPriceIdChanging(value);
                    ReportPropertyChanging("DayPriceId");
                    _DayPriceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DayPriceId");
                    OnDayPriceIdChanged();
                }
            }
        }
        private global::System.Guid _DayPriceId;
        partial void OnDayPriceIdChanging(global::System.Guid value);
        partial void OnDayPriceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SymbolName
        {
            get
            {
                return _SymbolName;
            }
            set
            {
                if (_SymbolName != value)
                {
                    OnSymbolNameChanging(value);
                    ReportPropertyChanging("SymbolName");
                    _SymbolName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SymbolName");
                    OnSymbolNameChanged();
                }
            }
        }
        private global::System.String _SymbolName;
        partial void OnSymbolNameChanging(global::System.String value);
        partial void OnSymbolNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DayPriceDate
        {
            get
            {
                return _DayPriceDate;
            }
            set
            {
                OnDayPriceDateChanging(value);
                ReportPropertyChanging("DayPriceDate");
                _DayPriceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceDate");
                OnDayPriceDateChanged();
            }
        }
        private global::System.DateTime _DayPriceDate;
        partial void OnDayPriceDateChanging(global::System.DateTime value);
        partial void OnDayPriceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceOpen
        {
            get
            {
                return _DayPriceOpen;
            }
            set
            {
                OnDayPriceOpenChanging(value);
                ReportPropertyChanging("DayPriceOpen");
                _DayPriceOpen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceOpen");
                OnDayPriceOpenChanged();
            }
        }
        private global::System.Decimal _DayPriceOpen;
        partial void OnDayPriceOpenChanging(global::System.Decimal value);
        partial void OnDayPriceOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceHigh
        {
            get
            {
                return _DayPriceHigh;
            }
            set
            {
                OnDayPriceHighChanging(value);
                ReportPropertyChanging("DayPriceHigh");
                _DayPriceHigh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceHigh");
                OnDayPriceHighChanged();
            }
        }
        private global::System.Decimal _DayPriceHigh;
        partial void OnDayPriceHighChanging(global::System.Decimal value);
        partial void OnDayPriceHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceLow
        {
            get
            {
                return _DayPriceLow;
            }
            set
            {
                OnDayPriceLowChanging(value);
                ReportPropertyChanging("DayPriceLow");
                _DayPriceLow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceLow");
                OnDayPriceLowChanged();
            }
        }
        private global::System.Decimal _DayPriceLow;
        partial void OnDayPriceLowChanging(global::System.Decimal value);
        partial void OnDayPriceLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceClose
        {
            get
            {
                return _DayPriceClose;
            }
            set
            {
                OnDayPriceCloseChanging(value);
                ReportPropertyChanging("DayPriceClose");
                _DayPriceClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceClose");
                OnDayPriceCloseChanged();
            }
        }
        private global::System.Decimal _DayPriceClose;
        partial void OnDayPriceCloseChanging(global::System.Decimal value);
        partial void OnDayPriceCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceAdjustedClose
        {
            get
            {
                return _DayPriceAdjustedClose;
            }
            set
            {
                OnDayPriceAdjustedCloseChanging(value);
                ReportPropertyChanging("DayPriceAdjustedClose");
                _DayPriceAdjustedClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceAdjustedClose");
                OnDayPriceAdjustedCloseChanged();
            }
        }
        private global::System.Decimal _DayPriceAdjustedClose;
        partial void OnDayPriceAdjustedCloseChanging(global::System.Decimal value);
        partial void OnDayPriceAdjustedCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DayPriceVolume
        {
            get
            {
                return _DayPriceVolume;
            }
            set
            {
                OnDayPriceVolumeChanging(value);
                ReportPropertyChanging("DayPriceVolume");
                _DayPriceVolume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceVolume");
                OnDayPriceVolumeChanged();
            }
        }
        private global::System.Int64 _DayPriceVolume;
        partial void OnDayPriceVolumeChanging(global::System.Int64 value);
        partial void OnDayPriceVolumeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportWatchModel", "FK_Day_Symbol", "SymbolSet")]
        public Symbol Symbol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Day_Symbol", "SymbolSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Day_Symbol", "SymbolSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Symbol> SymbolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Day_Symbol", "SymbolSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Symbol>("ReportWatchModel.FK_Day_Symbol", "SymbolSet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportWatchModel", Name="ExceptionLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExceptionLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExceptionLog object.
        /// </summary>
        /// <param name="exceptionLogId">Initial value of the ExceptionLogId property.</param>
        /// <param name="exceptionLogDate">Initial value of the ExceptionLogDate property.</param>
        /// <param name="exceptionLogMessage">Initial value of the ExceptionLogMessage property.</param>
        /// <param name="exceptionLogStackTrace">Initial value of the ExceptionLogStackTrace property.</param>
        public static ExceptionLog CreateExceptionLog(global::System.Guid exceptionLogId, global::System.DateTime exceptionLogDate, global::System.String exceptionLogMessage, global::System.String exceptionLogStackTrace)
        {
            ExceptionLog exceptionLog = new ExceptionLog();
            exceptionLog.ExceptionLogId = exceptionLogId;
            exceptionLog.ExceptionLogDate = exceptionLogDate;
            exceptionLog.ExceptionLogMessage = exceptionLogMessage;
            exceptionLog.ExceptionLogStackTrace = exceptionLogStackTrace;
            return exceptionLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ExceptionLogId
        {
            get
            {
                return _ExceptionLogId;
            }
            set
            {
                if (_ExceptionLogId != value)
                {
                    OnExceptionLogIdChanging(value);
                    ReportPropertyChanging("ExceptionLogId");
                    _ExceptionLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExceptionLogId");
                    OnExceptionLogIdChanged();
                }
            }
        }
        private global::System.Guid _ExceptionLogId;
        partial void OnExceptionLogIdChanging(global::System.Guid value);
        partial void OnExceptionLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExceptionLogDate
        {
            get
            {
                return _ExceptionLogDate;
            }
            set
            {
                OnExceptionLogDateChanging(value);
                ReportPropertyChanging("ExceptionLogDate");
                _ExceptionLogDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExceptionLogDate");
                OnExceptionLogDateChanged();
            }
        }
        private global::System.DateTime _ExceptionLogDate;
        partial void OnExceptionLogDateChanging(global::System.DateTime value);
        partial void OnExceptionLogDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionLogMessage
        {
            get
            {
                return _ExceptionLogMessage;
            }
            set
            {
                OnExceptionLogMessageChanging(value);
                ReportPropertyChanging("ExceptionLogMessage");
                _ExceptionLogMessage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionLogMessage");
                OnExceptionLogMessageChanged();
            }
        }
        private global::System.String _ExceptionLogMessage;
        partial void OnExceptionLogMessageChanging(global::System.String value);
        partial void OnExceptionLogMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionLogStackTrace
        {
            get
            {
                return _ExceptionLogStackTrace;
            }
            set
            {
                OnExceptionLogStackTraceChanging(value);
                ReportPropertyChanging("ExceptionLogStackTrace");
                _ExceptionLogStackTrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionLogStackTrace");
                OnExceptionLogStackTraceChanged();
            }
        }
        private global::System.String _ExceptionLogStackTrace;
        partial void OnExceptionLogStackTraceChanging(global::System.String value);
        partial void OnExceptionLogStackTraceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportWatchModel", Name="Report")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Report : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="reportId">Initial value of the ReportId property.</param>
        /// <param name="symbolName">Initial value of the SymbolName property.</param>
        /// <param name="reportDate">Initial value of the ReportDate property.</param>
        /// <param name="reportActual">Initial value of the ReportActual property.</param>
        /// <param name="reportExpected">Initial value of the ReportExpected property.</param>
        /// <param name="reportPreviousYear">Initial value of the ReportPreviousYear property.</param>
        /// <param name="dayPriceHigh">Initial value of the DayPriceHigh property.</param>
        /// <param name="reportName">Initial value of the ReportName property.</param>
        /// <param name="reportTitle">Initial value of the ReportTitle property.</param>
        public static Report CreateReport(global::System.Guid reportId, global::System.String symbolName, global::System.DateTime reportDate, global::System.Decimal reportActual, global::System.Decimal reportExpected, global::System.Decimal reportPreviousYear, global::System.Decimal dayPriceHigh, global::System.String reportName, global::System.String reportTitle)
        {
            Report report = new Report();
            report.ReportId = reportId;
            report.SymbolName = symbolName;
            report.ReportDate = reportDate;
            report.ReportActual = reportActual;
            report.ReportExpected = reportExpected;
            report.ReportPreviousYear = reportPreviousYear;
            report.DayPriceHigh = dayPriceHigh;
            report.ReportName = reportName;
            report.ReportTitle = reportTitle;
            return report;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                if (_ReportId != value)
                {
                    OnReportIdChanging(value);
                    ReportPropertyChanging("ReportId");
                    _ReportId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReportId");
                    OnReportIdChanged();
                }
            }
        }
        private global::System.Guid _ReportId;
        partial void OnReportIdChanging(global::System.Guid value);
        partial void OnReportIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SymbolName
        {
            get
            {
                return _SymbolName;
            }
            set
            {
                if (_SymbolName != value)
                {
                    OnSymbolNameChanging(value);
                    ReportPropertyChanging("SymbolName");
                    _SymbolName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SymbolName");
                    OnSymbolNameChanged();
                }
            }
        }
        private global::System.String _SymbolName;
        partial void OnSymbolNameChanging(global::System.String value);
        partial void OnSymbolNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReportDate
        {
            get
            {
                return _ReportDate;
            }
            set
            {
                OnReportDateChanging(value);
                ReportPropertyChanging("ReportDate");
                _ReportDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportDate");
                OnReportDateChanged();
            }
        }
        private global::System.DateTime _ReportDate;
        partial void OnReportDateChanging(global::System.DateTime value);
        partial void OnReportDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReportActual
        {
            get
            {
                return _ReportActual;
            }
            set
            {
                OnReportActualChanging(value);
                ReportPropertyChanging("ReportActual");
                _ReportActual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportActual");
                OnReportActualChanged();
            }
        }
        private global::System.Decimal _ReportActual;
        partial void OnReportActualChanging(global::System.Decimal value);
        partial void OnReportActualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReportExpected
        {
            get
            {
                return _ReportExpected;
            }
            set
            {
                OnReportExpectedChanging(value);
                ReportPropertyChanging("ReportExpected");
                _ReportExpected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportExpected");
                OnReportExpectedChanged();
            }
        }
        private global::System.Decimal _ReportExpected;
        partial void OnReportExpectedChanging(global::System.Decimal value);
        partial void OnReportExpectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReportPreviousYear
        {
            get
            {
                return _ReportPreviousYear;
            }
            set
            {
                OnReportPreviousYearChanging(value);
                ReportPropertyChanging("ReportPreviousYear");
                _ReportPreviousYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportPreviousYear");
                OnReportPreviousYearChanged();
            }
        }
        private global::System.Decimal _ReportPreviousYear;
        partial void OnReportPreviousYearChanging(global::System.Decimal value);
        partial void OnReportPreviousYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DayPriceHigh
        {
            get
            {
                return _DayPriceHigh;
            }
            set
            {
                OnDayPriceHighChanging(value);
                ReportPropertyChanging("DayPriceHigh");
                _DayPriceHigh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPriceHigh");
                OnDayPriceHighChanged();
            }
        }
        private global::System.Decimal _DayPriceHigh;
        partial void OnDayPriceHighChanging(global::System.Decimal value);
        partial void OnDayPriceHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReportName
        {
            get
            {
                return _ReportName;
            }
            set
            {
                OnReportNameChanging(value);
                ReportPropertyChanging("ReportName");
                _ReportName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReportName");
                OnReportNameChanged();
            }
        }
        private global::System.String _ReportName;
        partial void OnReportNameChanging(global::System.String value);
        partial void OnReportNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReportTitle
        {
            get
            {
                return _ReportTitle;
            }
            set
            {
                OnReportTitleChanging(value);
                ReportPropertyChanging("ReportTitle");
                _ReportTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReportTitle");
                OnReportTitleChanged();
            }
        }
        private global::System.String _ReportTitle;
        partial void OnReportTitleChanging(global::System.String value);
        partial void OnReportTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportWatchModel", "FK_Report_Symbol", "SymbolSet")]
        public Symbol Symbol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Report_Symbol", "SymbolSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Report_Symbol", "SymbolSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Symbol> SymbolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("ReportWatchModel.FK_Report_Symbol", "SymbolSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Symbol>("ReportWatchModel.FK_Report_Symbol", "SymbolSet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportWatchModel", Name="Symbol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Symbol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Symbol object.
        /// </summary>
        /// <param name="symbolName">Initial value of the SymbolName property.</param>
        /// <param name="indexSymbolName">Initial value of the IndexSymbolName property.</param>
        /// <param name="companyName">Initial value of the CompanyName property.</param>
        public static Symbol CreateSymbol(global::System.String symbolName, global::System.String indexSymbolName, global::System.String companyName)
        {
            Symbol symbol = new Symbol();
            symbol.SymbolName = symbolName;
            symbol.IndexSymbolName = indexSymbolName;
            symbol.CompanyName = companyName;
            return symbol;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SymbolName
        {
            get
            {
                return _SymbolName;
            }
            set
            {
                if (_SymbolName != value)
                {
                    OnSymbolNameChanging(value);
                    ReportPropertyChanging("SymbolName");
                    _SymbolName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SymbolName");
                    OnSymbolNameChanged();
                }
            }
        }
        private global::System.String _SymbolName;
        partial void OnSymbolNameChanging(global::System.String value);
        partial void OnSymbolNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IndexSymbolName
        {
            get
            {
                return _IndexSymbolName;
            }
            set
            {
                OnIndexSymbolNameChanging(value);
                ReportPropertyChanging("IndexSymbolName");
                _IndexSymbolName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IndexSymbolName");
                OnIndexSymbolNameChanged();
            }
        }
        private global::System.String _IndexSymbolName;
        partial void OnIndexSymbolNameChanging(global::System.String value);
        partial void OnIndexSymbolNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReportDate
        {
            get
            {
                return _ReportDate;
            }
            set
            {
                OnReportDateChanging(value);
                ReportPropertyChanging("ReportDate");
                _ReportDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportDate");
                OnReportDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReportDate;
        partial void OnReportDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReportDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportWatchModel", "FK_Day_Symbol", "DayPriceSet")]
        public EntityCollection<DayPrice> DayPriceSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DayPrice>("ReportWatchModel.FK_Day_Symbol", "DayPriceSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DayPrice>("ReportWatchModel.FK_Day_Symbol", "DayPriceSet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportWatchModel", "FK_Report_Symbol", "ReportSet")]
        public EntityCollection<Report> ReportSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Report>("ReportWatchModel.FK_Report_Symbol", "ReportSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Report>("ReportWatchModel.FK_Report_Symbol", "ReportSet", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
